site_name: BSA Lab Manuals
nav:
    - Lab Manuals:
        - SES250 Electromagnatics: 'ses250/index.md'
        - SEH500 Microprocessors: 'seh500/index.md'
        - SEP600 Embedded Systems: 'sep600/index.md'
        - SEA700 Robotics: 'sea700/index.md'

theme:
    name: readthedocs
    titles_only: true
    collapse_navigation: true
    prev_next_buttons_location: none

markdown_extensions:
    - mdx_math

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
    - css/extra.css