site_name: BSA Lab Manuals
nav:
    - SES250 Lab Manual:
        - 'Lab Instruction': 'ses250/instruction.md'
        - 'Lab Safety': 'ses250/safety.md'
        - 'Lab 1': 'ses250/lab1.md'
        - 'Lab 2': 'ses250/lab2.md'
        - 'Lab 3': 'ses250/lab3.md'
        - 'Lab 4': 'ses250/lab4.md'
        - 'Lab 5': 'ses250/lab5.md'
        - 'Lab 6': 'ses250/lab6.md'
        - 'Lab 7': 'ses250/lab7.md'
        - 'Lab 8': 'ses250/lab8.md'
        - 'Lab 9': 'ses250/lab9.md'
        - 'Lab 10': 'ses250/lab10.md'
    - SEH500 Lab Manual:
        - 'Lab Outline': 'seh500/index.md'
theme:
    name: readthedocs
extra_css:
    - css/extra.css

